[build]
  functions = "netlify/functions"
  publish   = "."

# السماح لـ CORS عشان الواجهة اللي على Hostinger تعرف تنادي الـ Function
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "POST, OPTIONS"
